# Generated by Django 5.1.3 on 2025-01-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='id_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
